### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by soffes** [max/node-alfalfabet#2]
You could actually have some for different languages, but that might be a bit too… useful for such a module.

**Comment by paulstraw** [comment]
This repo should really be called `node-alfalfabet-en`. Once that's done, other modules can be made for separate languages/dialects: `node-alfalfabet-en-us`, `node-alfalfabet-en-gb`, `node-alfalfabet-ar-sa`, `node-alfalfabet-fr`, `node-alfalfabet-it-ch`, etc.. Microsoft provides a good list [here](https://msdn.microsoft.com/en-us/library/ms533052%28v=vs.85%29.aspx) (which, let's be honest, should probably be modularized into a separate page for each language).

**Comment by soffes** [comment]
+1 `node-alfalfabet-en-us` & `node-alfalfabet-en-gb`

**Comment by seanwash** [comment]
When can we expect an ETA for this? :+1:

**Comment by max** [comment]
Not interested in trivial changes like this. Module works as expected in a large [production environment](https://github.com/max/alfalfie).
